package com.learn.wolaytegna.spokenwolaytic;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ListView;
import android.widget.Toast;

import java.util.ArrayList;

public class Main24Activity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);
        setTitle("Expressing likes & dislikes");

        ListView listView = findViewById(R.id.list_item);

        Categories1 cata1 = new Categories1("ASKING YES/NO QUESTIONS ABOUT INTERESTS AND LIKES\n\n\n- Do you like....?", "Neeni ... dosay?", R.raw.record20210321201839);
        Categories1 cata2 = new Categories1("RESPONSES\n\n- Yes, I do", "Ee, dosays.", R.raw.record20210321201843);
        Categories1 cata3 = new Categories1("Yes, very much", "Ee keehi dosays", R.raw.record20210321201849);
        Categories1 cata4 = new Categories1("Yes, I do very much", "Ee keehi dosays", R.raw.record20210321201855);
        Categories1 cata5 = new Categories1("Yes, a lot", "Ee daro dosays.", R.raw.record20210321201902);
        Categories1 cata6 = new Categories1("Yes, I do a lot", "Ee keehi dosays.", R.raw.record20210321201907);
        Categories1 cata7 = new Categories1("Yes, I love it/you/them", "Ee keehi hegaa dosays/A dosays/Eta dosays.", R.raw.record20210321201926);
        Categories1 cata8 = new Categories1("ASKING\n\n- Do you enjoy...?", "Neeni .... ufayttay?", R.raw.record20210321201934);
        Categories1 cata9 = new Categories1("RESPONSES\n\n- Yes, very much indeed.", "Ee keehippe tuma.", R.raw.record20210321201941);
        Categories1 cata10 = new Categories1("Yes, very much indeed.", "Ee, taani A keehi dosays, tuma.", R.raw.record20210321201953);
        Categories1 cata11 = new Categories1("Yes, I like you/them very much indeed.", "Ee, taani inttena/ Eta daro dosays tuma.", R.raw.record20210321202011);
        Categories1 cata12 = new Categories1("ASKING\n\n-Are you interested...?", "Neeni ... dosadii?", R.raw.record20210321202020);
        Categories1 cata13 = new Categories1("RESPONSES\n\n-Yes, actually I am", "Ee, taani dosaas.", R.raw.record20210321202026);
        Categories1 cata14 = new Categories1("Yes, as a matter of fact I do", "Ee, tumaappe ufayssis.", R.raw.record20210321202035);
        Categories1 cata15 = new Categories1("Yes, it's all right", "Ee, lo'o(injetiis)", R.raw.record20210321202041);
        Categories1 cata16 = new Categories1("Yes, it's ok.", "Ee, injje", R.raw.record20210321202047);
        Categories1 cata17 = new Categories1("ASKING\n\n- Have you got any favorite...?", "Dosadii?", R.raw.record20210321202053);
        Categories1 cata18 = new Categories1("Have you got any favorite...?", "Neeni dosiyo...demmadii?", R.raw.record20210321202102);
        Categories1 cata19 = new Categories1("Have you got any favorite...?", "Neeni dooriyo...demmadii?", R.raw.record20210321202119);
        Categories1 cata20 = new Categories1("RESPONSES\n\n-Well actually...", "Ee, taani dosaas.", R.raw.record20210321202125);
        Categories1 cata21 = new Categories1("Well frankly", "Ee, tumaappe.", R.raw.record20210321202131);
        Categories1 cata22 = new Categories1("Well frankly speaking", "Tuma, haasayikko ee", R.raw.record20210321202137);
        Categories1 cata23 = new Categories1("Well, I prefer", "Ero, taani .... doorays", R.raw.record20210321202159);
        Categories1 cata24 = new Categories1("Well, to be honest", "Ero xilluwa odanawu", R.raw.record20210321202208);
        Categories1 cata25 = new Categories1("Well, as a matter of fact", "... Ee, tuma odanawu", R.raw.record20210321202219);
        Categories1 cata26 = new Categories1("Well, I'm more into", "Ero, waayi hegaa taani dosana.", R.raw.record20210321202233);
        Categories1 cata27 = new Categories1("No I'm afraid I'm not", "Chi, waayi hegaa taani dosana.", R.raw.record20210321202240);
        Categories1 cata28 = new Categories1("No, I'm afraid I don't", "Akkay, taassi hegee waayi de'ana", R.raw.record20210321202251);
        Categories1 cata29 = new Categories1("ASKING 'WHY' QUESTIONS ABOUT INTERESTS AND LIKES\n\n\nASKING\n\n- What are your favorite...?", "Ne dosiyo...aybatee?",R.raw.record20210321202259);
        Categories1 cata30 = new Categories1("What are your favorite...?", "Ne dooriyo...aybatee?", R.raw.record20210321202307);
        Categories1 cata31 = new Categories1("RESPONSES\n\n- I'm rather interested in...", "Taani keehippe dooriyoy...", R.raw.record20210321202313);
        Categories1 cata32 = new Categories1("I'm rather quite keen on", "Taani keehippe ...doorays.", R.raw.record20210321202320);
        Categories1 cata33 = new Categories1("ASKING\n\n- What kind of ...are you interested in?", "Ay qommo .... neeni dosiyoy?", R.raw.record20210321202329);
        Categories1 cata34 = new Categories1("I quite like...", "Taani keehi dosiyoy...", R.raw.record20210321202342);
        Categories1 cata35 = new Categories1("I'm keen on", "Taani daroppe...dosays", R.raw.record20210321202350);
        Categories1 cata36 = new Categories1("I rather like...", "Taani daroppe ... dosays", R.raw.record20210321202350);
        Categories1 cata37 = new Categories1("Oh, I love...", "Taani...siqays.", R.raw.record20210321202356);
        Categories1 cata38 = new Categories1("EXPRESSING DISLIKES\n\n\n- No, I don't", "Chi, taani dosikke", R.raw.record20210321202420);
        Categories1 cata39 = new Categories1("No, I don't like it/you/them at all", "Akkay, taani hegaa/nena/eta muleka dosikke.", R.raw.record20210321202430);
        Categories1 cata40 = new Categories1("No, I don't care about it", "Chi, taani hegaa aynne yayyikke", R.raw.record20210321202441);
        Categories1 cata41 = new Categories1("No, not much", "Chi, darenna.", R.raw.record20210321202448);
        Categories1 cata42 = new Categories1("No, not particularly", "Chi hegaa dummayada dosikke.", R.raw.record20210321202454);
        Categories1 cata43 = new Categories1("I realy hate", "Taani tumuppe ixxays", R.raw.record20210321202501);
        Categories1 cata44 = new Categories1("...is not my favorite...", "...ta dooruwa gidenna.", R.raw.record20210321202508);
        Categories1 cata45 = new Categories1("EXPRESSING STRONG DISLIKE\n\n\n- I hate....", "Taani .... ixxays.", R.raw.record20210321202515);
        Categories1 cata46 = new Categories1("I dislike...", "Taani ...dosikke.", R.raw.record20210321202519);
        Categories1 cata47 = new Categories1("I don't speacially like...", "Taani ubakka ... dosikke.", R.raw.record20210321202549);
        Categories1 cata48 = new Categories1("I don't specially enjoy.", "Tana... ufayssenna.", R.raw.record20210321202555);
        Categories1 cata49 = new Categories1("EXPRESSING AGREEMENT WITH SOME BODY'S LIKES\n\n\n- So do I as a matter of fact...", "Taanikka, tumaappe dosays.", R.raw.record20210321202602);
        Categories1 cata50 = new Categories1("So am I, actuallu...", "Taanikka, tumuppe dosays...", R.raw.record20210321202642);
        Categories1 cata51 = new Categories1("I do too, as a matter offact", "Taanikka, tumuppe dosays.", R.raw.record20210321202701);
        Categories1 cata52 = new Categories1("I am actually ....", "Taanika ... tumuppe", R.raw.record20210321202711);
        Categories1 cata53 = new Categories1("EXPRESSING AGREEMENT WITH SOMEBODY'S DISLIKES\n\n\n- Neither do I, as a matter of fact...", "Taanikka dosikke, tumaa odikko.", R.raw.record20210321202736);
        Categories1 cata54= new Categories1("I don't either as a matter of fact...", "Taanikka nenatto, dosikke", R.raw.record20210321202756);
        Categories1 cata55 = new Categories1("Nor am I, actually...", "Taanikka ne mala, dosikke.", R.raw.record20210321202810);
        Categories1 cata56 = new Categories1("I am not either actually...", "Taanikka negaa mala dosikke.", R.raw.record20210321202818);
        Categories1 cata57 = new Categories1("Nor can, I actually ...", "Taanikka neega mala dosikke.", R.raw.record20210321202828);



        ArrayList<Categories1> list = new ArrayList<>();
        list.add(cata1);
        list.add(cata2);
        list.add(cata3);
        list.add(cata4);
        list.add(cata5);
        list.add(cata6);
        list.add(cata7);
        list.add(cata8);
        list.add(cata9);
        list.add(cata10);
        list.add(cata11);
        list.add(cata12);
        list.add(cata13);
        list.add(cata14);
        list.add(cata15);
        list.add(cata16);
        list.add(cata17);
        list.add(cata18);
        list.add(cata19);
        list.add(cata20);
        list.add(cata21);
        list.add(cata22);
        list.add(cata23);
        list.add(cata24);
        list.add(cata25);
        list.add(cata26);
        list.add(cata27);
        list.add(cata28);
        list.add(cata29);
        list.add(cata30);
        list.add(cata31);
        list.add(cata32);
        list.add(cata33);
        list.add(cata34);
        list.add(cata35);
        list.add(cata36);
        list.add(cata37);
        list.add(cata38);
        list.add(cata39);
        list.add(cata40);
        list.add(cata41);
        list.add(cata42);
        list.add(cata43);
        list.add(cata44);
        list.add(cata45);
        list.add(cata46);
        list.add(cata47);
        list.add(cata48);
        list.add(cata49);
        list.add(cata50);
        list.add(cata51);
        list.add(cata52);
        list.add(cata53);
        list.add(cata54);
        list.add(cata55);
        list.add(cata56);
        list.add(cata57);

        CategoriesListAdapter2 adapter = new CategoriesListAdapter2(this, R.layout.custom_layout2, list);
        listView.setAdapter(adapter);

        int num = new DBAdarter(Main24Activity.this).nof_alldata();
        Toast.makeText(Main24Activity.this, String.valueOf(num), Toast.LENGTH_SHORT).show();
        if (num == 591){
            new DBAdarter(Main24Activity.this).saveAllData(cata1);
            new DBAdarter(Main24Activity.this).saveAllData(cata2);
            new DBAdarter(Main24Activity.this).saveAllData(cata3);
            new DBAdarter(Main24Activity.this).saveAllData(cata4);
            new DBAdarter(Main24Activity.this).saveAllData(cata5);
            new DBAdarter(Main24Activity.this).saveAllData(cata6);
            new DBAdarter(Main24Activity.this).saveAllData(cata7);
            new DBAdarter(Main24Activity.this).saveAllData(cata8);
            new DBAdarter(Main24Activity.this).saveAllData(cata9);
            new DBAdarter(Main24Activity.this).saveAllData(cata10);
            new DBAdarter(Main24Activity.this).saveAllData(cata11);
            new DBAdarter(Main24Activity.this).saveAllData(cata12);
            new DBAdarter(Main24Activity.this).saveAllData(cata13);
            new DBAdarter(Main24Activity.this).saveAllData(cata14);
            new DBAdarter(Main24Activity.this).saveAllData(cata15);
            new DBAdarter(Main24Activity.this).saveAllData(cata16);
            new DBAdarter(Main24Activity.this).saveAllData(cata17);
            new DBAdarter(Main24Activity.this).saveAllData(cata18);
            new DBAdarter(Main24Activity.this).saveAllData(cata19);
            new DBAdarter(Main24Activity.this).saveAllData(cata20);
            new DBAdarter(Main24Activity.this).saveAllData(cata21);
            new DBAdarter(Main24Activity.this).saveAllData(cata22);
            new DBAdarter(Main24Activity.this).saveAllData(cata23);
            new DBAdarter(Main24Activity.this).saveAllData(cata24);
            new DBAdarter(Main24Activity.this).saveAllData(cata25);
            new DBAdarter(Main24Activity.this).saveAllData(cata26);
            new DBAdarter(Main24Activity.this).saveAllData(cata27);
            new DBAdarter(Main24Activity.this).saveAllData(cata28);
            new DBAdarter(Main24Activity.this).saveAllData(cata29);
            new DBAdarter(Main24Activity.this).saveAllData(cata30);
            new DBAdarter(Main24Activity.this).saveAllData(cata31);
            new DBAdarter(Main24Activity.this).saveAllData(cata32);
            new DBAdarter(Main24Activity.this).saveAllData(cata33);
            new DBAdarter(Main24Activity.this).saveAllData(cata34);
            new DBAdarter(Main24Activity.this).saveAllData(cata35);
            new DBAdarter(Main24Activity.this).saveAllData(cata36);
            new DBAdarter(Main24Activity.this).saveAllData(cata37);
            new DBAdarter(Main24Activity.this).saveAllData(cata38);
            new DBAdarter(Main24Activity.this).saveAllData(cata39);
            new DBAdarter(Main24Activity.this).saveAllData(cata40);
            new DBAdarter(Main24Activity.this).saveAllData(cata41);
            new DBAdarter(Main24Activity.this).saveAllData(cata42);
            new DBAdarter(Main24Activity.this).saveAllData(cata43);
            new DBAdarter(Main24Activity.this).saveAllData(cata44);
            new DBAdarter(Main24Activity.this).saveAllData(cata45);
            new DBAdarter(Main24Activity.this).saveAllData(cata46);
            new DBAdarter(Main24Activity.this).saveAllData(cata47);
            new DBAdarter(Main24Activity.this).saveAllData(cata48);
            new DBAdarter(Main24Activity.this).saveAllData(cata49);
            new DBAdarter(Main24Activity.this).saveAllData(cata50);
            new DBAdarter(Main24Activity.this).saveAllData(cata51);
            new DBAdarter(Main24Activity.this).saveAllData(cata52);
            new DBAdarter(Main24Activity.this).saveAllData(cata53);
            new DBAdarter(Main24Activity.this).saveAllData(cata54);
            new DBAdarter(Main24Activity.this).saveAllData(cata55);
            new DBAdarter(Main24Activity.this).saveAllData(cata56);
            new DBAdarter(Main24Activity.this).saveAllData(cata57);
        }
    }
}
