package com.learn.wolaytegna.spokenwolaytic;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ListView;
import android.widget.Toast;

import java.util.ArrayList;

public class Main19Activity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);
        setTitle("Home life");

        ListView listView = findViewById(R.id.list_item);
        Categories1 cata1 = new Categories1("DESCRIBING FAMILY RELATIONSHIPS\n\nLike father. Like son.", "Ba aawaa duutti ekkida na'a", R.raw.record20210321192542);
        Categories1 cata2 = new Categories1("He is the spiting image of his grandfather.", "Ba aawaa aawaa mule misatees.", R.raw.record20210321192638);
        Categories1 cata3 = new Categories1("She is a real daddy's girl.", "A tumuppe ba aawaa milatawusu.", R.raw.record20210321192651);
        Categories1 cata4 = new Categories1("You are hust like your mother.", "Ne mule ne aayyiyo milataasa.", R.raw.record20210321192710);
        Categories1 cata5 = new Categories1("She exactly resembles her aunt.", "A ba aayyee michchiyo mule dutta ekkasu.", R.raw.record20210321192720);
        Categories1 cata6 = new Categories1("You're your father all over again.", "Ne muleera ne aawaa milataasa.", R.raw.record20210321192732);
        Categories1 cata7 = new Categories1("You take after your father.", "Ne aawaa tokkadasa.", R.raw.record20210321192745);
        Categories1 cata8 = new Categories1("PRAISING A SMALL CHILD\n\nGood boy!", "Lo'o na'a", R.raw.record20210321192752);
        Categories1 cata9 = new Categories1("Good girl!", "Lo'o macca na'a.", R.raw.record20210321192800);
        Categories1 cata10 = new Categories1("That is very good.", "Hegee daro lo'o.", R.raw.record20210321192806);
        Categories1 cata11 = new Categories1("Momy's proud of you.", "Ne aayyeedan nena bonchchana.", R.raw.record20210321192820);
        Categories1 cata12 = new Categories1("You're a good little boy(girl)", "Neeni lo'o attuma/macca na'a", R.raw.record20210321192857);
        Categories1 cata13 = new Categories1("Big boy! What a big girl!", "Gita na'a! ne ayba gita na'ee", R.raw.record20210321192907);
        Categories1 cata14 = new Categories1("I'm so proud of you.", "Taani nenan keehippe bonchchataas.", R.raw.record20210321192917);
        Categories1 cata15 = new Categories1("SCOLDING A CHILD\n\nBe good!", "Lo'o na'a gida", R.raw.record20210321192924);
        Categories1 cata16 = new Categories1("Behave!", "Woppu ga!", R.raw.record20210321192931);
        Categories1 cata17 = new Categories1("That is enough of that!", "Hegee hegawu gidana", R.raw.record20210321192940);
        Categories1 cata18 = new Categories1("Be a good girl/boy!", "Lo'o na'a/na'iyo gida", R.raw.record20210321192953);
        Categories1 cata19 = new Categories1("Behave yourself!", "Nenaadan hana", R.raw.record20210321193000);
        Categories1 cata20 = new Categories1("INSTRUCTION CHILDREN TO FINISH EATING\n\nFinish your dinner", "Ne kahuwaa wurssa.", R.raw.record20210321193017);
        Categories1 cata21 = new Categories1("You have to eat everything", "Neeni ubbabaakka maanawu koshshees.", R.raw.record20210321193026);
        Categories1 cata22 = new Categories1("You have to clean up your plate.", "Neeni saaniyappe quuccada maanawu koshshees.",R.raw.record20210321193033);
        Categories1 cata23 = new Categories1("You have to eat some of everything.", "Neeni ubbabbaappekka guuttaa maanawu koshshees.", R.raw.record20210321193041);
        Categories1 cata24 = new Categories1("INSTRUCTING CHILDREN ON GOOD TABLE MANNER\n\nDon't read at the table", "Qumaa maydda nabbaboppa", R.raw.record20210321193049);
        Categories1 cata25 = new Categories1("Don't talk with your mouth full.", "Qumay doonan de'ishin haasayoppa", R.raw.record20210321193056);
        Categories1 cata26 = new Categories1("No TV during dinner.", "Kahuwaa maydda Televizhiniya xeelloppa", R.raw.record20210321193104);
        Categories1 cata27 = new Categories1("Wipe your mouth", "Ne doonaa qucca.", R.raw.record20210321193122);
        Categories1 cata28 = new Categories1("Don't put your elbows on the table.", "Qumaa miyo masopiyan ne qesiya wottoppa.", R.raw.record20210321193141);
        Categories1 cata29 = new Categories1("SENDING A CHILD TO BED\n\nGo to bed.", "Hixaakko ba", R.raw.record20210321193147);
        Categories1 cata30 = new Categories1("It's time to go to bed.", "Hegee hixaakko biyo wode", R.raw.record20210321193203);
        Categories1 cata31 = new Categories1("It's past your bed time.", "Ne xiskko satee aadhdhiis", R.raw.record20210321193210);
        Categories1 cata32 = new Categories1("Off to bed now.", "Ha'i zin'a", R.raw.record20210321193218);
        Categories1 cata33 = new Categories1("It's bed time.", "Hagee zin'iyo wode.", R.raw.record20210321193223);
        Categories1 cata34 = new Categories1("MAKING SURE A CHILD UNDERSTANDS\n\nIs that clear?", "Hagee niyo qonccee?", R.raw.record20210321193232);
        Categories1 cata35 = new Categories1("Do as I say.", "Ta giidoogaadan ootta", R.raw.record20210321193246);
        Categories1 cata36 = new Categories1("Do as i tell you.", "Ta niyo odidoogaadan ootta", R.raw.record20210321193258);
        Categories1 cata37 = new Categories1("Do as I say, not as I do.", "Ta niyo odidoogaadan ootta, ta oottiyoogaadan Oottoppa.", R.raw.record20210321193318);
        Categories1 cata38 = new Categories1("Do you hear?", "Siyadii?", R.raw.record20210321193326);
        Categories1 cata39 = new Categories1("Did you hear me?", "Tana siyadii?", R.raw.record20210321193330);
        Categories1 cata40 = new Categories1("Have I made my self clear?", "Ta giidobaa niyo qoncce oottoo?", R.raw.record20210321193338);
        Categories1 cata41 = new Categories1("GIVING A CHILD INSTRUCTION FOR CLEANNESS\n\nGo wash your hands.", "Ba ne kushiya meecetta!", R.raw.record20210321193344);
        Categories1 cata42 = new Categories1("Go wash your face.", "Ba ne som'uwaa meecetta!", R.raw.record20210321193350);
        Categories1 cata43 = new Categories1("Go brush your teeth", "Ba ne achchaa miiqqa!", R.raw.record20210321193358);
        Categories1 cata44 = new Categories1("Combo your hair", "Ne huuphiyaa pixa!", R.raw.record20210321193403);
        Categories1 cata45 = new Categories1("Clean up your room", "Ne kifiliya pitta!", R.raw.record20210321193408);
        Categories1 cata46 = new Categories1("Pick up your room.", "Ne kifiliyaappe dentta", R.raw.record20210321193413);
        Categories1 cata47 = new Categories1("Pick up your clothes.", "Ne maayuwa dentta!", R.raw.record20210321193419);
        Categories1 cata48 = new Categories1("Put your toys away", "Ne Ashanggulutiya hagaappe digga", R.raw.record20210321193430);
        Categories1 cata49 = new Categories1("Make your bed.", "Ne Arssaa hiixxa.", R.raw.record20210321193441);
        Categories1 cata50 = new Categories1("GIVING A CHILD INSTRUCTION FOR TV WATCHING\n\nMove back from the TV.", "Televizhiniyaappe haakkada utta", R.raw.record20210321193448);
        Categories1 cata51 = new Categories1("Turn that racket down(noise)", "Ane cenggurssaa guutta", R.raw.record20210321193457);
        Categories1 cata52 = new Categories1("Turn that thing off.", "A cenggurssa  gordda", R.raw.record20210321193518);
        Categories1 cata53 = new Categories1("Turn that music down.", "A muuziiqaa guutta", R.raw.record20210321193525);
        Categories1 cata54 = new Categories1("CONCERNING A CHILD'S HOME WORK\n\nDo you have any home work tonight?", "Hachchi omarssan oottanawu imettida so oosoy niyo de'ii?",R.raw.record20210321193537);
        Categories1 cata55 = new Categories1("Did you finish your homework?", "Ne so oosuwa wurssadii?", R.raw.record20210321193553);
        //error56
        Categories1 cata56 = new Categories1("Don't forget to take your home work to school.", "Niyo imettida so oosuwa timirtte keettaa ekka biyoogaa dogoppa.", R.raw.record20210321193619);
        Categories1 cata57 = new Categories1("Let's see your home work.", "Ane ne so oosuwa be'oos.", R.raw.record20210321193635);
        Categories1 cata58 = new Categories1("You can't watch TV until you finish your home work.", "Ne so oosuwa ootta wurssana gakkanawu televizhiniya xeelloppa.",R.raw.record20210321193652);
        Categories1 cata59 = new Categories1("WHEN CHILDREN BICKER\n\nI'm telling", "Niyo odays", R.raw.record20210321193705);
        Categories1 cata60 = new Categories1("Leave me alone.", "Tana aggarkkii", R.raw.record20210321193710);
        Categories1 cata61 = new Categories1("I'm telling mom", "Ne aayyeessi odana.", R.raw.record20210321193721);
        Categories1 cata62 = new Categories1("Stop picking on me.", "Tana geniyooga aggarkkii?", R.raw.record20210321193728);
        Categories1 cata63 = new Categories1("I'm going to tell on you.", "Niyo ta odays.", R.raw.record20210321193733);
        Categories1 cata64 = new Categories1("POSING QUESTIONS TO CHILDREN\n\nWhat is your name , Kid?", "La na'wu, ne sunttay oonee?", R.raw.record20210321193739);
        Categories1 cata65 = new Categories1("What grade are you in?", "Aappuntta kiffiliyaan de'ay?", R.raw.record20210321193751);
        Categories1 cata66 = new Categories1("Do you go to school yet?", "Timirtte keettaa gam'ada geladii?", R.raw.record20210321193810);
        Categories1 cata67 = new Categories1("How many brothers do you have?", "Aappun ishati niyo de'iyoonaa?", R.raw.record20210321193816);
        Categories1 cata68 = new Categories1("What's your favorite class in school?", "Ne timirtte Kettan ay qommo timirttya dossay?", R.raw.record20210321193826);
        Categories1 cata69 = new Categories1("GOING TO BED AND SLEEP\n\nI'm going to crash", "Taani guuttaa liphphi gays.", R.raw.record20210321193843);
        Categories1 cata70 = new Categories1("I'm going to sleep", "Taani xiskkananays.", R.raw.record20210321193851);
        Categories1 cata71 = new Categories1("I'm off to bed.", "Ane liphphi gays", R.raw.record20210321193857);
        Categories1 cata72 = new Categories1("I'm going to hit the sack.", "Taani xiskkuwa shoca ekkays", R.raw.record20210321193904);
        Categories1 cata73 = new Categories1("It's past my bed time", "Ta xiskkuwa wodee aadhdhis", R.raw.record20210321193910);
        Categories1 cata74 = new Categories1("I think I'll retire for the night", "Ta qoppiyo mala ha omarssan daafuraas shemppana koyyays.", R.raw.record20210321193921);
        Categories1 cata75 = new Categories1("CONCERNING PREGNANCY\n\n She is pregnant", "A shaara", R.raw.record20210321193930);
        Categories1 cata76 = new Categories1("She is with child", "A na'aara de'awusu", R.raw.record20210321193936);
        Categories1 cata77 = new Categories1("She is in a family way", "A so asaa medhdhydda de'awusu", R.raw.record20210321193942);
        Categories1 cata78 = new Categories1("When are you due?", "Ne awude yelay?", R.raw.record20210321193955);


        ArrayList<Categories1> list = new ArrayList<>();
        list.add(cata1);
        list.add(cata2);
        list.add(cata3);
        list.add(cata4);
        list.add(cata5);
        list.add(cata6);
        list.add(cata7);
        list.add(cata8);
        list.add(cata9);
        list.add(cata10);
        list.add(cata11);
        list.add(cata12);
        list.add(cata13);
        list.add(cata14);
        list.add(cata15);
        list.add(cata16);
        list.add(cata17);
        list.add(cata18);
        list.add(cata19);
        list.add(cata20);
        list.add(cata21);
        list.add(cata22);
        list.add(cata23);
        list.add(cata24);
        list.add(cata25);
        list.add(cata26);
        list.add(cata27);
        list.add(cata28);
        list.add(cata29);
        list.add(cata30);
        list.add(cata31);
        list.add(cata32);
        list.add(cata33);
        list.add(cata34);
        list.add(cata35);
        list.add(cata36);
        list.add(cata37);
        list.add(cata38);
        list.add(cata39);
        list.add(cata40);
        list.add(cata41);
        list.add(cata42);
        list.add(cata43);
        list.add(cata44);
        list.add(cata45);
        list.add(cata46);
        list.add(cata47);
        list.add(cata48);
        list.add(cata49);
        list.add(cata50);
        list.add(cata51);
        list.add(cata52);
        list.add(cata53);
        list.add(cata54);
        list.add(cata55);
        list.add(cata56);
        list.add(cata57);
        list.add(cata58);
        list.add(cata59);
        list.add(cata60);
        list.add(cata61);
        list.add(cata62);
        list.add(cata63);
        list.add(cata64);
        list.add(cata65);
        list.add(cata66);
        list.add(cata67);
        list.add(cata68);
        list.add(cata69);
        list.add(cata70);
        list.add(cata71);
        list.add(cata72);
        list.add(cata73);
        list.add(cata74);
        list.add(cata75);
        list.add(cata76);
        list.add(cata77);
        list.add(cata78);

        CategoriesListAdapter2 adapter = new CategoriesListAdapter2(this, R.layout.custom_layout2, list);
        listView.setAdapter(adapter);

        int num = new DBAdarter(Main19Activity.this).nof_alldata();
        Toast.makeText(Main19Activity.this, String.valueOf(num), Toast.LENGTH_SHORT).show();
        if (num == 350){
            new DBAdarter(Main19Activity.this).saveAllData(cata1);
            new DBAdarter(Main19Activity.this).saveAllData(cata2);
            new DBAdarter(Main19Activity.this).saveAllData(cata3);
            new DBAdarter(Main19Activity.this).saveAllData(cata4);
            new DBAdarter(Main19Activity.this).saveAllData(cata5);
            new DBAdarter(Main19Activity.this).saveAllData(cata6);
            new DBAdarter(Main19Activity.this).saveAllData(cata7);
            new DBAdarter(Main19Activity.this).saveAllData(cata8);
            new DBAdarter(Main19Activity.this).saveAllData(cata9);
            new DBAdarter(Main19Activity.this).saveAllData(cata10);
            new DBAdarter(Main19Activity.this).saveAllData(cata11);
            new DBAdarter(Main19Activity.this).saveAllData(cata12);
            new DBAdarter(Main19Activity.this).saveAllData(cata13);
            new DBAdarter(Main19Activity.this).saveAllData(cata14);
            new DBAdarter(Main19Activity.this).saveAllData(cata15);
            new DBAdarter(Main19Activity.this).saveAllData(cata16);
            new DBAdarter(Main19Activity.this).saveAllData(cata17);
            new DBAdarter(Main19Activity.this).saveAllData(cata18);
            new DBAdarter(Main19Activity.this).saveAllData(cata19);
            new DBAdarter(Main19Activity.this).saveAllData(cata20);
            new DBAdarter(Main19Activity.this).saveAllData(cata21);
            new DBAdarter(Main19Activity.this).saveAllData(cata22);
            new DBAdarter(Main19Activity.this).saveAllData(cata23);
            new DBAdarter(Main19Activity.this).saveAllData(cata24);
            new DBAdarter(Main19Activity.this).saveAllData(cata25);
            new DBAdarter(Main19Activity.this).saveAllData(cata26);
            new DBAdarter(Main19Activity.this).saveAllData(cata27);
            new DBAdarter(Main19Activity.this).saveAllData(cata28);
            new DBAdarter(Main19Activity.this).saveAllData(cata29);
            new DBAdarter(Main19Activity.this).saveAllData(cata30);
            new DBAdarter(Main19Activity.this).saveAllData(cata31);
            new DBAdarter(Main19Activity.this).saveAllData(cata32);
            new DBAdarter(Main19Activity.this).saveAllData(cata33);
            new DBAdarter(Main19Activity.this).saveAllData(cata34);
            new DBAdarter(Main19Activity.this).saveAllData(cata35);
            new DBAdarter(Main19Activity.this).saveAllData(cata36);
            new DBAdarter(Main19Activity.this).saveAllData(cata37);
            new DBAdarter(Main19Activity.this).saveAllData(cata38);
            new DBAdarter(Main19Activity.this).saveAllData(cata39);
            new DBAdarter(Main19Activity.this).saveAllData(cata40);
            new DBAdarter(Main19Activity.this).saveAllData(cata41);
            new DBAdarter(Main19Activity.this).saveAllData(cata42);
            new DBAdarter(Main19Activity.this).saveAllData(cata43);
            new DBAdarter(Main19Activity.this).saveAllData(cata44);
            new DBAdarter(Main19Activity.this).saveAllData(cata45);
            new DBAdarter(Main19Activity.this).saveAllData(cata46);
            new DBAdarter(Main19Activity.this).saveAllData(cata47);
            new DBAdarter(Main19Activity.this).saveAllData(cata48);
            new DBAdarter(Main19Activity.this).saveAllData(cata49);
            new DBAdarter(Main19Activity.this).saveAllData(cata50);
            new DBAdarter(Main19Activity.this).saveAllData(cata51);
            new DBAdarter(Main19Activity.this).saveAllData(cata52);
            new DBAdarter(Main19Activity.this).saveAllData(cata53);
            new DBAdarter(Main19Activity.this).saveAllData(cata54);
            new DBAdarter(Main19Activity.this).saveAllData(cata55);
            new DBAdarter(Main19Activity.this).saveAllData(cata56);
            new DBAdarter(Main19Activity.this).saveAllData(cata57);
            new DBAdarter(Main19Activity.this).saveAllData(cata58);
            new DBAdarter(Main19Activity.this).saveAllData(cata59);
            new DBAdarter(Main19Activity.this).saveAllData(cata60);
            new DBAdarter(Main19Activity.this).saveAllData(cata61);
            new DBAdarter(Main19Activity.this).saveAllData(cata62);
            new DBAdarter(Main19Activity.this).saveAllData(cata63);
            new DBAdarter(Main19Activity.this).saveAllData(cata64);
            new DBAdarter(Main19Activity.this).saveAllData(cata65);
            new DBAdarter(Main19Activity.this).saveAllData(cata66);
            new DBAdarter(Main19Activity.this).saveAllData(cata67);
            new DBAdarter(Main19Activity.this).saveAllData(cata68);
            new DBAdarter(Main19Activity.this).saveAllData(cata69);
            new DBAdarter(Main19Activity.this).saveAllData(cata70);
            new DBAdarter(Main19Activity.this).saveAllData(cata71);
            new DBAdarter(Main19Activity.this).saveAllData(cata72);
            new DBAdarter(Main19Activity.this).saveAllData(cata73);
            new DBAdarter(Main19Activity.this).saveAllData(cata74);
            new DBAdarter(Main19Activity.this).saveAllData(cata75);
            new DBAdarter(Main19Activity.this).saveAllData(cata76);
            new DBAdarter(Main19Activity.this).saveAllData(cata77);
            new DBAdarter(Main19Activity.this).saveAllData(cata78);
        }
    }
}
